include /env.mak

obj-m += raptorlakes-synobios.o

raptorlakes-synobios-objs = \
	../common/common.o \
	../syno_ttyS/syno_ttyS.o \
	../synobios.o \
	rs4025xs+.o \
	../mapping.o \
	../rtc/localtime.o \
	../rtc/alarmtime.o \
	../rtc/rtc-seiko-lib.o \
	../rtc/rtc-linux-seiko.o \
	../i2c/i2c-linux.o \
	../pmbus/pmbus.o \
	raptorlakes_common.o \
	../led/led_trigger.o
